### ISSUE TITLE
Menus hosed after upgrade from 2.2.12-13 to 2.2.12-14

### ISSUE THREAD

**Issue by wildstar84** [Remmy/afterstep#6]
![Uploading 2015-04-22-135918_1920x1080_scrot.png . . .]()
![Uploading 2015-04-22-135918_1920x1080_scrot.png . . .]()

I've now stumbled upon an even bigger issue, only affecting latest AS (2.2.12-14).  After upgrading the deb from snapshot.debian.org (afterstep-data, afterstep), the popup system menus are now non-existant (see image of menu popup).  Looks like it's expecting them in a different place or different format? (zero menu items), though everything's still in place.  My menus are all in /usr/share/afterstep/start/

Sample menu file  ("4_xterminal"):
Exec "XTerminal" exec x-terminal-emulator -T "XTerminal@`hostname --long`" &
MiniPixmap "mini-app.xpm"

To check my configuration, I tried renaming my .afterstep directory and running AS so that came up in default configuratoin, same results!  Any updates / workarounds?!

Thanks!

Jim

my "base" file:
 ModulePath		/usr/bin
 IconPath			/usr/share/pixmaps:$HOME/images
 FontPath 			/usr/share/fonts/X11/misc:/usr/share/fonts/X11/100dpi:/usr/share/fonts/X11/Type1:/usr/share/fonts/truetype/freefont:/usr/share/afterstep/desktop/fonts
 PixmapPath		/usr/share/pixmaps:/usr/share/afterstep/desktop/icons:/usr/share/afterstep/desktop/buttons:$HOME/.afterstep/backgrounds:/usr/share/afterstep/backgrounds:$HOME/images
 CursorPath              $HOME/.afterstep/desktop/cursors:/usr/share/afterstep/desktop/cursors
 ScriptPath		$HOME/.afterstep/scripts/:/usr/share/afterstep/scripts/

 Pertinent "Feel" file settings:
MenuMiniPixmaps 0
RecentMenuItems 5
DecorateTransients
Mouse 3         R       A       PopUp "0" 0
Mouse 2         R       A       WindowList "0"
Key Menu        A       A       Popup "Start Menu" 0
Key Menu        A       C       WindowList 2
Key Menu        A       S       WindowList

**Comment by wildstar84** [comment]
NEVER MIND!!!!  Pbm was I didn't upgrade these 2 lib packages! (dpkg did NOT report the versions as dependencies?!):
libafterimage0_2.2.12-4_i386.deb
libafterstep1_2.2.12-4_i386.deb

Did these and all is well now!  (Nothing like reporting an issue to enable one to suddenly discover how to fix it) :D

Jim Turner

**Comment by Remmy** [comment]
On Wed, Apr 22, 2015 at 12:36:06PM -0700, wildstar84 wrote in 
<Remmy/afterstep/issues/6/95312433@github.com>:
>NEVER MIND!!!!  Pbm was I didn't upgrade these 2 lib packages! (dpkg did NOT report the versions as dependencies?!):
>libafterimage0_2.2.12-4_i386.deb
>libafterstep1_2.2.12-4_i386.deb
>
>Did these and all is well now!  (Nothing like reporting an issue to enable one to suddenly discover how to fix it) :D

Hi Jim,

Sounds like something worthy of filing a report on in the debian bug 
tracker if this is indeed the cause of this problem. If it is, that 
dependency should have been explicitly declared.

Cheers,

Remco
